JWT_TOKEN_SECRET=""

DATABASE_DSN=""
DATABASE_USER=""
DATABASE_PASSWORD=""

MU_SECRET=""

DISCORD_CLIENT_ID=""
DISCORD_CLIENT_SECRET=""

GOOGLE_CLIENT_ID=""

GITHUB_APP_ID=""
GITHUB_INSTALLATION_ID=""
GITHUB_OWNER=""
GITHUB_REPOSITORY=""
GITHUB_BASE_BRANCH=""
GITHUB_JWT_PRIVATE_KEY=""